babel ./src/orderBook/order-book.js --out-file ./src/orderBook/order-book-translate.js
babel ./src/wallet/wallet-org.js --out-file ./src/wallet/wallet.js
babel ./src/wallet/walletUtils-org.js --out-file ./src/wallet/walletUtils.js
babel ./src/wallet/bidsAsks-org.js --out-file ./src/wallet/bidsAsks.js
babel ./src/wallet/yield-org.js --out-file ./src/wallet/yieldPayment.js
babel ./src/wallet/depositCoins-org.js --out-file ./src/wallet/depositCoins.js
babel ./src/wallet/userDisposition-org.js --out-file ./src/wallet/userDisposition.js
babel ./src/wallet/userFeesState-org.js --out-file ./src/wallet/userFeesState.js
babel ./src/wallet/internalAccount-org.js --out-file ./src/wallet/internalAccount.js
babel ./src/wallet/initialProject-org.js --out-file ./src/wallet/initialProject.js
babel ./src/wallet/mortgageCalculator-org.js --out-file ./src/wallet/mortgageCalculator.js
