export const types = {
  LISTEN_FOR_PROJECT_TRADE_STATS: "LISTEN_FOR_PROJECT_TRADE_STATS",
  STOP_LISTEN_FOR_PROJECT_TRADE_STATS: "STOP_LISTEN_FOR_PROJECT_TRADE_STATS",
  SET_PROJECT_ASKS: "SET_PROJECT_ASKS",
  SET_PROJECT_MORTGAGE: "SET_PROJECT_MORTGAGE",
  SET_PROJECT_MORTGAGE_REQUEST: "SET_PROJECT_MORTGAGE_REQUEST",
  SET_PROJECT_BIDS: "SET_PROJECT_BIDS",
  SET_PROJECT_HISTORY_TRADES: "SET_PROJECT_HISTORY_TRADES",
  SET_PROJECT_PENDING_ORDERS: "SET_PROJECT_PENDING_ORDERS",
  SET_PROJECT_HOLDINGS: "SET_PROJECT_HOLDINGS",
  SET_PROJECT_AUCTION_ASKS: "SET_PROJECT_AUCTION_ASKS",
  SET_PROJECT_AUCTION_BIDS: "SET_PROJECT_AUCTION_BIDS"
};

export const listenForProject = project => {
  return {
    type: types.LISTEN_FOR_PROJECT_TRADE_STATS,
    project
  };
};

export const stopListenForProject = project => {
  return {
    type: types.STOP_LISTEN_FOR_PROJECT_TRADE_STATS,
    project
  };
};
